# Generated by Django 4.2.13 on 2024-07-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('EmployeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date_of_Joining', models.DateField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
