# Generated by Django 4.2.13 on 2024-07-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing_EMP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False},
        ),
    ]
