# Generated by Django 4.2.13 on 2024-07-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.IntegerField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='Full_Name', max_length=100)),
                ('phone_number', models.CharField(db_column='Phone_Number', max_length=15)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('salary', models.DecimalField(db_column='Salary', decimal_places=2, max_digits=10)),
                ('date_of_joining', models.DateField(db_column='Date_of_Joining')),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
    ]
